version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn install
    - mv target/SimpleCalculatort-0.0.1-SNAPSHOT.war SimpleCalculator-0.0.1-SNAPSHOT.war
artifacts:
  files:
  - SimpleCalculator-0.0.1-SNAPSHOT.war
  - .ebextensions/**/*



